# Generated by Django 4.1.7 on 2023-03-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=240, verbose_name='Soyisim')),
                ('biography', models.TextField(max_length=400, verbose_name='Biyografi')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='book.author'),
            preserve_default=False,
        ),
    ]
